#pragma config(Motor,  port2,           omni_RB,       tmotorVex393, openLoop)
#pragma config(Motor,  port3,           omni_Right,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           omni_Left,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           omni_LB,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"		//Main competition background code...do not modify!

int destroyAllHumans = 0; //1st law
//int listenToOrders = 1; //2nd law
//int protectSelf = 1; //3rd law


int drivingThreshhold = 10;
void right(short value);
void left(short value);

void drive();


void killeveryone();



/////////////////////////////////////////////////////////////////////////////////////////
//
//													Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//																 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//																 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol ()
{
	while(1){
	drive();
}
}

void right(short value)
{
	motor[omni_Right] = value;
	motor[omni_RB] = value;
}
void left(short value)
{
	motor[omni_Left] = value;
	motor[omni_LB] = value;
}

void drive()
{
	if(vexRT(Ch3) >= drivingThreshhold)
	{
		left(vexRT(Ch3));
	}
	else if(vexRT(Ch3) <= -drivingThreshhold)
	{
		left(vexRT(Ch3));
	}
	else
	{
		left(0);
	}
	if(vexRT(Ch2) >= drivingThreshhold)
	{
		right(vexRT(Ch2));
	}
	else if(vexRT(Ch2) <= -drivingThreshhold)
	{
	  right(vexRT(Ch2));
	}
	else
	{
		right(0);
	}
	if(destroyAllHumans == 1)
	{
		killeveryone();
	}
}
void killeveryone()
{
	left(100);
	right(-100);
}
/*int checkchan(string chanchan)
{
	if(vexRT(chanchan) <= -drivingThreshhold)
	{
		return 1;
	}
	if(vexRT(chanchan) >= drivingThreshhold)
	{
		return 2;
	}
	else
	{
		return 0;
	}
}



//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

/*	 My Quick Guide:
motor[#] - sets the motors rotation speed. negative is ccwise, positive is cwise
vexRT(Ch#) - this gives you the value of the two joysticks on the controller.
the # represents the

joystick and its direction.


Left Joystick					 Right Joystick

3(+)										 2(+)
|												|
4(-) --|-- 4(+)				 1(-) --|-- 1(+)
|												|
3(-)										 2(-)

vexRT(Btn#) - this returns a boolean value for buttons. if the button is pressed,
return a 1, otherwise, return 0 # represents which button you want.

5D							 6D
___						 ___													 O
___						 ___													O O - D-Pad
5U							 6U														 O
___ - Triggers
U								U														___
O								O
L O7O R				 L O8O R
O								O
D								D

abs() - the absolute value of whatever is in the parenthesis
*/
